const flowerData = [
    {
      id: 1,
      img: "flower1.jpg",
      title: "Rose Bouquet",
      description: "A beautiful bouquet of fresh red roses.",
      star: 4.5,
      reviews: 120,
      price: 19.99,
      company: "Floral Paradise",
      color: "Red",
      category: "Rose",
      availability: true,
      stock: 50,
      tags: ["romantic", "special occasion", "gift"],
      sizes: ["Small", "Medium", "Large"],
      deliveryOptions: {
        standard: {
          fee: 5.99,
          timeframe: "3-5 business days",
        },
        express: {
          fee: 12.99,
          timeframe: "1-2 business days",
        },
      },
    },
    {
      id: 2,
      img: "flower2.jpg",
      title: "Tulip Arrangement",
      description: "A stunning arrangement of colorful tulips.",
      star: 4.3,
      reviews: 95,
      price: 29.99,
      company: "Tulip Treasures",
      color: "Various",
      category: "Tulip",
      availability: true,
      stock: 40,
      tags: ["spring", "fresh", "vibrant"],
      sizes: ["Small", "Medium"],
      deliveryOptions: {
        standard: {
          fee: 6.99,
          timeframe: "3-5 business days",
        },
        express: {
          fee: 14.99,
          timeframe: "1-2 business days",
        },
      },
    },
    {
      id: 3,
      img: "flower3.jpg",
      title: "Lily Bouquet",
      description: "An elegant bouquet of fragrant lilies.",
      star: 4.7,
      reviews: 150,
      price: 34.99,
      company: "Lily Lane",
      color: "White",
      category: "Lily",
      availability: true,
      stock: 60,
      tags: ["elegant", "fragrant", "occasion"],
      sizes: ["Medium", "Large"],
      deliveryOptions: {
        standard: {
          fee: 7.99,
          timeframe: "4-6 business days",
        },
        express: {
          fee: 16.99,
          timeframe: "2-3 business days",
        },
      },
    },
    {
      id: 4,
      img: "flower4.jpg",
      title: "Orchid Plant",
      description: "A graceful orchid plant in a decorative pot.",
      star: 4.8,
      reviews: 180,
      price: 39.99,
      company: "Orchid Oasis",
      color: "Purple",
      category: "Orchid",
      availability: true,
      stock: 30,
      tags: ["graceful", "indoor", "decor"],
      sizes: ["Large"],
      deliveryOptions: {
        standard: {
          fee: 8.99,
          timeframe: "4-6 business days",
        },
        express: {
          fee: 18.99,
          timeframe: "2-3 business days",
        },
      },
    },
    {
      id: 5,
      img: "flower5.jpg",
      title: "Daisy Bouquet",
      description: "A charming bouquet of bright daisies and greenery.",
      star: 4.4,
      reviews: 100,
      price: 22.99,
      company: "Daisy Delights",
      color: "Yellow",
      category: "Daisy",
      availability: true,
      stock: 45,
      tags: ["charming", "cheerful", "simple"],
      sizes: ["Small", "Medium"],
      deliveryOptions: {
        standard: {
          fee: 5.49,
          timeframe: "3-5 business days",
        },
        express: {
          fee: 11.49,
          timeframe: "1-2 business days",
        },
      },
    },
    {
      id: 6,
      img: "flower6.jpg",
      title: "Carnation Bouquet",
      description: "A classic bouquet of vibrant carnations.",
      star: 4.6,
      reviews: 130,
      price: 26.99,
      company: "Carnation Co.",
      color: "Pink",
      category: "Carnation",
      availability: true,
      stock: 55,
      tags: ["classic", "vibrant", "versatile"],
      sizes: ["Medium", "Large"],
      deliveryOptions: {
        standard: {
          fee: 6.49,
          timeframe: "3-5 business days",
        },
        express: {
          fee: 13.49,
          timeframe: "1-2 business days",
        },
      },
    },
    {
      id: 7,
      img: "flower7.jpg",
      title: "Peony Bouquet",
      description: "An extravagant bouquet of luxurious peonies.",
      star: 4.9,
      reviews: 200,
      price: 49.99,
      company: "Peony Palace",
      color: "Pink",
      category: "Peony",
      availability: true,
      stock: 25,
      tags: ["extravagant", "luxurious", "premium"],
      sizes: ["Large"],
      deliveryOptions: {
        standard: {
          fee: 9.99,
          timeframe: "4-6 business days",
        },
        express: {
          fee: 20.99,
          timeframe: "2-3 business days",
        },
      },
    },
    {
      id: 8,
      img: "flower8.jpg",
      title: "Hydrangea Arrangement",
      description: "A stunning arrangement of colorful hydrangeas.",
      star: 4.7,
      reviews: 150,
      price: 36.99,
      company: "Hydrangea Haven",
      color: "Blue",
      category: "Hydrangea",
      availability: true,
      stock: 35,
      tags: ["stunning", "colorful", "decorative"],
      sizes: ["Medium", "Large"],
      deliveryOptions: {
        standard: {
          fee: 7.99,
          timeframe: "4-6 business days",
        },
        express: {
          fee: 16.99,
          timeframe: "2-3 business days",
        },
      },
    },
    {
      id: 9,
      img: "flower9.jpg",
      title: "Gerbera Daisy Bouquet",
      description: "A vibrant bouquet of cheerful gerbera daisies.",
      star: 4.4,
      reviews: 100,
      price: 23.99,
      company: "Gerbera Gardens",
      color: "Various",
      category: "Gerbera",
      availability: true,
      stock: 40,
      tags: ["vibrant", "cheerful", "fun"],
      sizes: ["Small", "Medium"],
      deliveryOptions: {
        standard: {
          fee: 5.99,
          timeframe: "3-5 business days",
        },
        express: {
          fee: 12.99,
          timeframe: "1-2 business days",
        },
      },
    },
    {
      id: 10,
      img: "flower10.jpg",
      title: "Cactus Garden",
      description: "A low-maintenance indoor garden featuring a variety of cacti.",
      star: 4.0,
      reviews: 80,
      price: 31.99,
      company: "Desert Dream",
      color: "Various",
      category: "Cactus",
      availability: true,
      stock: 20,
      tags: ["low-maintenance", "indoor", "modern"],
      sizes: ["Small", "Medium"],
      deliveryOptions: {
        standard: {
          fee: 8.99,
          timeframe: "4-6 business days",
        },
        express: {
          fee: 17.99,
          timeframe: "2-3 business days",
        },
      },
    },
  ];
  
  export default flowerData;
  